# Generated by Django 5.2.4 on 2026-01-11 14:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("institute_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ELECTRICITY", "Electricity"),
                            ("FUEL", "Fuel"),
                            ("WATER", "Water"),
                            ("WASTE", "Waste"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        choices=[
                            ("GRID", "Grid Electricity"),
                            ("DIESEL", "Diesel"),
                            ("PETROL", "Petrol"),
                            ("LPG", "LPG"),
                            ("CNG", "CNG"),
                            ("MUNICIPAL_WATER", "Municipal Water"),
                            ("ORGANIC_WASTE", "Organic Waste"),
                            ("PLASTIC_WASTE", "Plastic Waste"),
                            ("E_WASTE", "E-Waste"),
                            ("GENERAL_WASTE", "General Waste"),
                        ],
                        max_length=50,
                    ),
                ),
                ("factor", models.FloatField(help_text="kg CO2e per unit")),
                (
                    "unit",
                    models.CharField(help_text="e.g., kWh, liter, kg", max_length=50),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Data source reference",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "sub_category")},
            },
        ),
        migrations.CreateModel(
            name="ConsumptionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HOSTEL", "Hostel"),
                            ("CANTEEN", "Canteen"),
                            ("ADMIN", "Administration"),
                            ("LABS", "Laboratories"),
                            ("TRANSPORT", "Transport"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "electricity_kwh",
                    models.FloatField(default=0, help_text="Electricity in kWh"),
                ),
                (
                    "diesel_liters",
                    models.FloatField(
                        default=0, help_text="Diesel consumption in liters"
                    ),
                ),
                (
                    "petrol_liters",
                    models.FloatField(
                        default=0, help_text="Petrol consumption in liters"
                    ),
                ),
                (
                    "lpg_kg",
                    models.FloatField(default=0, help_text="LPG consumption in kg"),
                ),
                (
                    "water_kl",
                    models.FloatField(
                        default=0, help_text="Water consumption in kiloliters"
                    ),
                ),
                (
                    "waste_kg",
                    models.FloatField(default=0, help_text="Waste generated in kg"),
                ),
                (
                    "electricity_emissions",
                    models.FloatField(default=0, help_text="kg CO2e from electricity"),
                ),
                (
                    "fuel_emissions",
                    models.FloatField(default=0, help_text="kg CO2e from fuels"),
                ),
                (
                    "water_emissions",
                    models.FloatField(default=0, help_text="kg CO2e from water"),
                ),
                (
                    "waste_emissions",
                    models.FloatField(default=0, help_text="kg CO2e from waste"),
                ),
                (
                    "total_emissions",
                    models.FloatField(default=0, help_text="Total kg CO2e"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("institute", "department", "date")},
            },
        ),
    ]
